=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/bic21subjects.dtd
<!--
  * dtd/bic21subjects.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2000-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD for BIC 2.1 Subject lists.
  *
  -->
<!ELEMENT subjects (subject+)>
<!ELEMENT subject EMPTY>
	<!ATTLIST subject 
		code CDATA #REQUIRED
		text CDATA #REQUIRED>

=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/locale/ar_IQ/bic21subjects.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE subjects SYSTEM "../../dtd/bic21subjects.dtd">
<!--
  * locale/ar_IQ/bic21subjects.xml
  *
  * Copyright BIC and Nielsen Book Services Ltd 2010
  *
  * localized list of BIC 2.1 Subjects
  * Reference:  http://www.bic.org.uk/7/BIC-Standard-Subject-Categories
  -->
<subjects>
	<subject code="A" text="الفنون" />
	<subject code="AB" text="الفنون: مواضيع عامة" />
	<subject code="ABA" text="نظرية الفن" />
	<subject code="ABC" text="صيانة، استعادة، عناية بالأعمال الفنية" />
	<subject code="ABK" text="التزوير والتزييف وسرقة الأعمال الفنية" />
	<subject code="ABQ" text="الفنون: النواحي المالية" />
	<subject code="AC" text="تأريخ الفن / الفن وأنماط التصميم" />
	<subject code="ACB" text="أنماط فنية غير محددة زمنياً" />
	<subject code="ACBK" text="فن الشعوب الأصلية" />
	<subject code="ACBN" text="الفن الساذج" />
	<subject code="ACBP" text="الفن الشرقي" />
	<subject code="ACBS" text="الفن الاستعماري" />
	<subject code="ACC" text="تأريخ الفن: ما قبل التأريخ" />
	<subject code="ACG" text="تأريخ الفن: الفن القديم والكلاسيكي، ما قبل الميلاد حتى 500 ميلادي" />
	<subject code="ACK" text="تأريخ الفن: الفن البيزنطي وفن العصور الوسطى، 500 إلى 1400 ميلادي" />
	<subject code="ACN" text="تأريخ الفن وأنماط التصميم: 1400 إلى 1600 ميلادي" />
	<subject code="ACND" text="فن عصر النهضة" />
	<subject code="ACNH" text="الفن وأساليب التصميم: التكلف" />
	<subject code="ACQ" text="تأريخ الفن وأنماط التصميم: 1600 إلى 1800 ميلادي" />
	<subject code="ACQB" text="الفن وأنماط التصميم: عصر الباروك" />
	<subject code="ACQH" text="الفن وأنماط التصميم: الكلاسيكية " />
	<subject code="ACV" text="تأريخ الفن وأنماط التصميم: 1800 إلى 1900" />
	<subject code="ACVC" text="الفن وأنماط التصميم: رومانتيكية" />
	<subject code="ACVM" text="الفن وأنماط التصميم: ما قبل الفن الرافايليتي" />
	<subject code="ACVN" text="الفن وأنماط التصميم: فنون وأساليب الحرف" />
	<subject code="ACVT" text="الفن وأنماط التصميم: الإنطباعية وما بعد الانطباعية" />
	<subject code="ACVY" text="الفن وأنماط التصميم: الفن الحديث" />
	<subject code="ACX" text="تأريخ الفن وأنماط التصميم: من 1900 حتى الآن" />
	<subject code="ACXD" text="الفن وأنماط التصميم: 1900 إلى 1960" />
	<subject code="ACXD1" text="الفن وأنماط التصميم: التعبيرية" />
	<subject code="ACXD2" text="الفن وأنماط التصميم: التصميم العصري وباوهاوس" />
	<subject code="ACXD3" text="الفن وأنماط التصميم: فن الديكور" />
	<subject code="ACXD5" text="الفن وأنماط التصميم: التكعيبية" />
	<subject code="ACXD7" text="الفن وأنماط التصميم: السريالية والدادائية" />
	<subject code="ACXD9" text="الفن وأنماط التصميم: التجريدية التعبيرية" />
	<subject code="ACXJ" text="الفن وأنماط التصميم: من 1960" />
	<subject code="ACXJ1" text="الفن وأنماط التصميم: الفن الشعبي" />
	<subject code="ACXJ4" text="الفن وأنماط التصميم: التبسيطية" />
	<subject code="ACXJ5" text="الفن وأنماط التصميم: الفن المفاهيمي" />
	<subject code="ACXJ8" text="الفن وأنماط التصميم: ما بعد الحداثة" />
	<subject code="AF" text="أشكال الفنون" />
	<subject code="AFC" text="الرسم واللوحات" />
	<subject code="AFCC" text="الألوان المائية" />
	<subject code="AFCL" text="الألوان الزيتية" />
	<subject code="AFF" text="الرسم والروسمات" />
	<subject code="AFH" text="المطبوعات وصناعة المطبوعات" />
	<subject code="AFJ" text="أشكال الفنون التخطيطية الأخرى" />
	<subject code="AFJD" text="الملصقات وتركيب الصور" />
	<subject code="AFJG" text="الكتابة على الجدران وفن الشوارع" />
	<subject code="AFK" text="أشكال الفن اللاتخطيطية" />
	<subject code="AFKB" text="نحت" />
	<subject code="AFKC" text="المنحوتات: الأعمال الفنية" />
	<subject code="AFKG" text="المعادن الثمينة، الأحجار الكريمة، المجوهرات: الأعمال الفنية والتصميم" />
	<subject code="AFKN" text="فن التركيب" />
	<subject code="AFKP" text="فن الأداء" />
	<subject code="AFKV" text="الفنون الالكترونية، الثلاثية الأبعاد، و الفديوية" />
	<subject code="AFP" text="فنون السيراميك والفخار والزجاج" />
	<subject code="AFPC" text="صناعة الخزف: الأعمال الفنية" />
	<subject code="AFPM" text="الفسيفساء: الأعمال الفنية" />
	<subject code="AFPS" text="الزجاج الملون: الأعمال الفنية" />
	<subject code="AFT" text="فنون الديكور" />
	<subject code="AFTB" text="الفن الشعبي" />
	<subject code="AFTC" text="الفنون الحرفية، الصناعات اليدوية" />
	<subject code="AFW" text="الأعمال الفنية النسيجية" />
	<subject code="AFWD" text="الأعمال الفنية النسيجية: السجاد والحصير" />
	<subject code="AFWH" text="الأعمال الفنية النسيجية: مطرزات، وتعاليق ولحفان" />
	<subject code="AFY" text="فنون الجسد والوشم" />
	<subject code="AG" text="المعالجات الفنية والمواضيع" />
	<subject code="AGB" text="الفنانون المنفردون والدراسات الفنية" />
	<subject code="AGC" text="كتلوكات المعارض والمجموعات الخاصة" />
	<subject code="AGH" text="الأشكال البشرية المصورة في الفن" />
	<subject code="AGHF" text="الصور الشخصية في الفن" />
	<subject code="AGHN" text="تصوير العري في الفن" />
	<subject code="AGHX" text="الفن الشهواني" />
	<subject code="AGK" text="المشاهد صغيرة الأبعاد، العلمانية، المحلية في الفن" />
	<subject code="AGN" text="الحيوانات والطبيعة في الفن (الحياة الجامدة، المناظر الطبيعية، المناظر البحرية... إلخ.)" />
	<subject code="AGNB" text="الفنون النباتية" />
	<subject code="AGP" text="تصوير المصنوعات في الفن (مناظر المدن، الآلات... إلخ.)" />
	<subject code="AGR" text="تصوير الموضوعات الدينية في الفن" />
	<subject code="AGZ" text="تقنيات الفن ومبادئه" />
	<subject code="AJ" text="التصوير الفوتوغرافي والصور الفوتوغرافية" />
	<subject code="AJB" text="المصورون الفوتوغرافيون المنفردون" />
	<subject code="AJC" text="التصوير الفوتوغرافي: مجموعات" />
	<subject code="AJCP" text="التصوير الفوتوغرافي: صور شخصية" />
	<subject code="AJCR" text="التقارير الفوتوغرافية" />
	<subject code="AJCX" text="التصوير الفوتوغرافي للعري وما يثير الشهوة" />
	<subject code="AJG" text="المعدات الفوتوغرافية وتقنياتها" />
	<subject code="AJR" text="أنواع خاصة من التصوير الفوتوغرافي" />
	<subject code="AJRD" text="أعمال التصوير السينمائي والتلفزيوني" />
	<subject code="AJRH" text="التصوير الفيديوي" />
	<subject code="AJRK" text="التصوير الجوي" />
	<subject code="AK" text="الفن الصناعي / التجاري والتصميم" />
	<subject code="AKB" text="مصممون منفردون" />
	<subject code="AKC" text="التصميم التخطيطي" />
	<subject code="AKD" text="الطباعة والكتابة" />
	<subject code="AKH" text="تصميم الكتب" />
	<subject code="AKL" text="الفن التوضيحي والتجاري" />
	<subject code="AKLB" text="المثال التوضيحي" />
	<subject code="AKLC" text="فن الكتاب الهزلي والرسوم المتحركة" />
	<subject code="AKLC1" text="فن الرواية المصورة والمانغا" />
	<subject code="AKLP" text="فن الملصقات" />
	<subject code="AKP" text="تصميم المنتجات" />
	<subject code="AKR" text="تصميم الآثاث" />
	<subject code="AKT" text="تصميم الأزياء والمنسوجات" />
	<subject code="AKTA" text="تصميم الأزياء ونظرياتها" />
	<subject code="AKTH" text="تأريخ تصميم الأزياء" />
	<subject code="AKTX" text="تصميم المنسوجات ونظرياتها" />
	<subject code="AM" text="الهندسة المعمارية" />
	<subject code="AMA" text="نظرية الهندسة المعمارية" />
	<subject code="AMB" text="المهندسون المعماريون المنفردون وشركات الهندسة المعمارية" />
	<subject code="AMC" text="البنية والتصميم المعماري" />
	<subject code="AMCR" text="الهندسة والتصميم المعماري الصديق للبيئة" />
	<subject code="AMD" text="الهندسة المعمارية: الممارسة المهنية" />
	<subject code="AMG" text="الأبنية العامة: المدنية، التجارية، الصناعية... إلخ." />
	<subject code="AMGC" text="قاعات الحفلات الموسيقية، الساحات، الملاعب" />
	<subject code="AMGD" text="النصب التذكارية والآثار" />
	<subject code="AMK" text="المباني السكنية والمباني المحلية" />
	<subject code="AMKD" text="المنازل والشقق وغيرها" />
	<subject code="AMKH" text="القصور والسرايات، البيوت الريفية" />
	<subject code="AMKL" text="القلاع والتحصينات" />
	<subject code="AMN" text="المباني الدينية" />
	<subject code="AMR" text="التصميم الداخلي الاحترافي" />
	<subject code="AMV" text="فن المناظر الطبيعية والهندسة المعمارية" />
	<subject code="AMVD" text="تخطيط المدن والقرى - جوانب معمارية" />
	<subject code="AMX" text="تأريخ العمارة" />
	<subject code="AN" text="الدراسات المسرحية" />
	<subject code="ANB" text="المسرح: ممثلون ومخرجون منفردون" />
	<subject code="ANC" text="تقنيات التمثيل" />
	<subject code="ANF" text="الإخراج والإنتاج المسرحي" />
	<subject code="ANH" text="المسرح: التقنيات والمهارات الأساسية" />
	<subject code="ANS" text="إدارة المسارح" />
	<subject code="AP" text="الأفلام، التلفاز، الإذاعة" />
	<subject code="APB" text="ممثلون ومؤدون منفردون" />
	<subject code="APF" text="الأفلام والسينما" />
	<subject code="APFA" text="النظرية والنقد الفلمي" />
	<subject code="APFB" text="مخرجو أفلام منفردون، صانعو الأفلام" />
	<subject code="APFD" text="النصوص الفلمية والسينمائية" />
	<subject code="APFG" text="الإرشادات والتنقيحات الفلمية" />
	<subject code="APFN" text="الأفلام: الأنماط والأنواع" />
	<subject code="APFR" text="الأفلام الوثائقية" />
	<subject code="APFV" text="الأفلام المتحركة" />
	<subject code="APFX" text="الإنتاج الفلمي: المهارات التقنية الأساسية" />
	<subject code="APT" text="التلفاز" />
	<subject code="APTD" text="النصوص التلفازية" />
	<subject code="APTS" text="المسلسلات التلفزيونية" />
	<subject code="APTX" text="الإنتاج التلفزيوني: التقنيات والمهارات الأساسية" />
	<subject code="APW" text="الإذاعة" />
	<subject code="APWD" text="النصوص الإذاعية" />
	<subject code="AS" text="الرقص وغيره من الفنون الأدائية" />
	<subject code="ASD" text="الرقص" />
	<subject code="ASDC" text="تصميم الرقصات" />
	<subject code="ASDL" text="رقص الباليه" />
	<subject code="ASDR" text="صالة الرقص" />
	<subject code="ASDT" text="الرقص المعاصر" />
	<subject code="ASDX" text="الرقص الشعبي" />
	<subject code="ASZ" text="فنون الأداء الأخرى" />
	<subject code="ASZB" text="فنون الأداء: الهزليات" />
	<subject code="ASZC" text="التمثيل الصامت" />
	<subject code="ASZD" text="مسرح الشارع" />
	<subject code="ASZG" text="السحر والشعوذة" />
	<subject code="ASZH" text="برامج المنوعات، وقاعات الموسيقى والملاهي الليلية" />
	<subject code="ASZJ" text="ألعاب الخفة" />
	<subject code="ASZM" text="مسرح الدمى والألعاب المصغرة theatre" />
