=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/genres.dtd
<!--
  * dtd/genres.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2000-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD for default genre settings.
  *
  -->
<!ELEMENT genres (genre+)>
<!ELEMENT genre EMPTY>
	<!ATTLIST genre
		key CDATA #REQUIRED
		category CDATA #REQUIRED
		dependent CDATA #REQUIRED
		supplementary CDATA #REQUIRED
		localeKey CDATA #REQUIRED>

=== H-Alexa/IIT-Journal-project-using-OJS/registry/genres.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE genres SYSTEM "../lib/pkp/dtd/genres.dtd">

<!--
  * registry/genres.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Default genres XML file.
  * N.B. The "category" attribute's value can be:
  *  1 => GENRE_CATEGORY_DOCUMENT
  *  2 => GENRE_CATEGORY_ARTWORK
  *  3 => GENRE_CATEGORY_SUPPLEMENTARY
  * These are defined in lib/pkp/classes/submission/Genre.inc.php.
  -->
<genres>
	<genre key="SUBMISSION" category="1" dependent="0" supplementary="0" localeKey="default.genres.article" />
	<genre key="RESEARCHINSTRUMENT" category="3" dependent="0" supplementary="1" localeKey="default.genres.researchInstrument" />
	<genre key="RESEARCHMATERIALS" category="3" dependent="0" supplementary="1" localeKey="default.genres.researchMaterials" />
	<genre key="RESEARCHRESULTS" category="3" dependent="0" supplementary="1" localeKey="default.genres.researchResults" />
	<genre key="TRANSCRIPTS" category="3" dependent="0" supplementary="1" localeKey="default.genres.transcripts" />
	<genre key="DATAANALYSIS" category="3" dependent="0" supplementary="1" localeKey="default.genres.dataAnalysis" />
	<genre key="DATASET" category="3" dependent="0" supplementary="1" localeKey="default.genres.dataSet" />
	<genre key="SOURCETEXTS" category="3" dependent="0" supplementary="1" localeKey="default.genres.sourceTexts" />
	<genre key="MULTIMEDIA" category="1" dependent="1" supplementary="1" localeKey="default.genres.multimedia" />
	<genre key="IMAGE" category="2" dependent="1" supplementary="0" localeKey="default.genres.image" />
	<genre key="STYLE" category="1" dependent="1" supplementary="0" localeKey="default.genres.styleSheet" />
	<genre key="OTHER" category="3" dependent="0" supplementary="1" localeKey="default.genres.other" />
</genres>
