=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/install.dtd
<!--
  * dtd/install.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD for installer descriptor files.
  *
  * Installer descriptor files list the set of XML database schema and data
  * files to parse and execute during installation.
  *
  * All file paths are relative to the location of this file.
  *
  * Note that for locale-specific data files, the string "{$locale}" appearing
  * in a file path will be replaced with the default locale selected at
  * installation time. Similarly, "{$installedLocale}" will be replaced with
  * each locale to be installed (i.e., that file will be installed for each
  * selected locale).
  *
  * Example:
  *
  * <install version="2.0.0.0">
  *    <schema file="ojs_schema.xml"/>
  *    <data file="data/common_data.xml"/>
  *    <data file="data/locale/{$locale}/locale_data.xml"/>
  * </install>
  *
  -->

<!ELEMENT install (schema?, data?, migration?, code?, note?, upgrade?)*>
	<!ATTLIST install
		version CDATA #IMPLIED>
<!ELEMENT upgrade (schema?, data?, migration?, code?, note?, upgrade?)+>
	<!ATTLIST upgrade
		minversion CDATA #IMPLIED
		maxversion CDATA #IMPLIED>
<!ELEMENT schema EMPTY>
	<!ATTLIST schema
		file CDATA #IMPLIED>
<!ELEMENT data EMPTY>
	<!ATTLIST data
		file CDATA #REQUIRED
		condition CDATA #IMPLIED>
<!ELEMENT migration EMPTY>
	<!ATTLIST migration
		class CDATA #REQUIRED>
<!ELEMENT code EMPTY>
	<!ATTLIST code
		message CDATA #IMPLIED
		file CDATA #IMPLIED
		class CDATA #IMPLIED
		function CDATA #REQUIRED
		locales CDATA #IMPLIED
		key CDATA #IMPLIED
		condition CDATA #IMPLIED>
<!ELEMENT note EMPTY>
	<!ATTLIST note
		file CDATA #REQUIRED>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "../../lib/pkp/dtd/install.dtd">
<!--
  * dbscripts/xml/upgrade.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Upgrade descriptor file.
  *
  -->

<install version="3.3.0.7">
	<code function="checkPhpVersion" />

	<upgrade minversion="2.0.0.0" maxversion="2.9.9.9">
		<!-- OJS < 3.0.0 upgrade unsupported -->
		<!-- OJS 3.0 alpha or beta to 3.0 upgrade unsupported -->
		<code function="abort" message="installer.unsupportedUpgradeError" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.0.1.9">
		<data file="dbscripts/xml/upgrade/3.0.0_preupdate_commentsToEditor.xml" condition="return $installer->columnExists('submissions', 'comments_to_ed');" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.0.9.9">
		<data file="dbscripts/xml/upgrade/3.1.0_preupdate_review_assignments.xml" condition="return $installer->columnExists('review_assignments', 'cancelled');" />
		<data file="dbscripts/xml/upgrade/3.1.0_preupdate_notes.xml" condition="return $installer->columnExists('notes', 'file_id');" />
		<data file="dbscripts/xml/upgrade/3.1.0_preupdate_payments.xml" condition="return $installer->columnExists('completed_payments', 'journal_id');" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.0.9">
		<data file="dbscripts/xml/upgrade/3.1.1_preupdate_citations.xml" condition="return $installer->columnExists('citations', 'assoc_type');" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.1.9">
		<data file="dbscripts/xml/upgrade/3.1.2_preupdate_user_author_names.xml" condition="return $installer->columnExists('users', 'first_name');" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.9.9">
		<code function="migrateSubmissionCoverImages" />
		<data file="dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml" />
		<data file="dbscripts/xml/upgrade/3.2.0_preupdate_versioning_articleGalleySettings.xml" condition="return $installer->tableExists('article_galley_settings');"/>
		<data file="dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml" />
		<data file="dbscripts/xml/upgrade/3.2.0_preupdate_last_activity.xml" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.9.9">
		<!-- Old schema syncs: These are deprecated! -->
		<schema file="lib/pkp/xml/schema/common.xml" />
		<schema file="lib/pkp/xml/schema/log.xml" />
		<schema file="lib/pkp/xml/schema/announcements.xml" />
		<schema file="lib/pkp/xml/schema/scheduledTasks.xml" />
		<schema file="lib/pkp/xml/schema/temporaryFiles.xml" />
		<schema file="lib/pkp/xml/schema/metadata.xml" />
		<schema file="lib/pkp/xml/schema/reviews.xml" />
		<schema file="lib/pkp/xml/schema/reviewForms.xml" />
		<schema file="lib/pkp/xml/schema/controlledVocab.xml" />
		<schema file="lib/pkp/xml/schema/submissions.xml" />
		<schema file="lib/pkp/xml/schema/submissionFiles.xml" />
		<schema file="lib/pkp/xml/schema/categories.xml" />
		<schema file="lib/pkp/xml/schema/notes.xml" />
		<schema file="lib/pkp/xml/schema/genres.xml" />
		<schema file="lib/pkp/xml/schema/tombstone.xml" />
		<schema file="lib/pkp/xml/schema/rolesAndUserGroups.xml" />
		<schema file="lib/pkp/xml/schema/metrics.xml" />
		<schema file="lib/pkp/xml/schema/views.xml" />
		<schema file="lib/pkp/xml/schema/libraryFiles.xml" />
		<schema file="lib/pkp/xml/schema/navigationMenus.xml" />
		<schema file="dbscripts/xml/ojs_schema.xml" />
	</upgrade>

	<!-- Install default NavigationMenus -->
	<code function="installDefaultNavigationMenus" />
	<code function="migrateStaticPagesToNavigationMenuItems" />

	<upgrade minversion="3.0.0.0" maxversion="3.1.1.9">
		<code function="migrateSRLocale" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.9.9">
		<!-- migrateUserAndAuthorNames should be after migrateSRLocale -->
		<code function="migrateUserAndAuthorNames" condition="return $installer->tableExists('users_tmp');" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.0.0.9">
		<code function="setFileUploader" />
		<data file="dbscripts/xml/upgrade/3.0.1_update.xml" />
		<data file="dbscripts/xml/upgrade/3.0.0_postupgrade_galley_files.xml" />
		<data file="dbscripts/xml/upgrade/3.0.0_postupgrade_metrics.xml" />
		<code function="localizeIssueCoverImages" />
		<code function="localizeArticleCoverImages" />
		<data file="dbscripts/xml/upgrade/3.0.0_issue_settings.xml" />
		<data file="dbscripts/xml/upgrade/3.0.0_submission_settings.xml" />
		<code function="installEmailTemplate" key="SUBMISSION_ACK_NOT_USER" locales="en_US,ca_ES,es_ES,fr_CA,pt_BR" />
		<data file="dbscripts/xml/upgrade/3.0.0_review_method.xml" />
		<data file="dbscripts/xml/upgrade/3.0.0_stage_assignments.xml" />
		<data file="dbscripts/xml/upgrade/3.0.0_edit_decisions.xml" />
		<code function="convertCommentsToEditor" condition="return $installer->tableExists('submissions_tmp');" />
		<note file="docs/release-notes/README-3.0.1" />
	</upgrade>

	<upgrade minversion="3.0.1.0" maxversion="3.0.1.9">
		<data file="dbscripts/xml/upgrade/3.0.0_review_method.xml" />
		<data file="dbscripts/xml/upgrade/3.0.0_stage_assignments.xml" />
		<data file="dbscripts/xml/upgrade/3.0.0_edit_decisions.xml" />
		<code function="clearCssCache" />
		<code function="convertCommentsToEditor" condition="return $installer->tableExists('submissions_tmp');" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.0.1.9">
		<data file="dbscripts/xml/upgrade/3.0.2_update.xml" />
		<note file="docs/release-notes/README-3.0.2" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.0.9.9">
		<code function="installEmailTemplate" key="PASSWORD_RESET" locales="ca_ES,cs_CZ,da_DK,de_DE,en_US,es_ES,eu_ES,fi_FI,fr_CA,hr_HR,id_ID,it_IT,nb_NO,nl_NL,pt_BR,pt_PT,ru_RU,sv_SE,tr_TR,uk_UA,zh_CN" />
		<data file="dbscripts/xml/upgrade/3.1.0_update_a.xml" />
		<code function="fixGenreIdInFileNames" />
		<code function="repairKeywordsAndSubjects" />
		<code function="enabledSitePlugins" />
		<code function="moveCSSFiles" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.0.9.9">
		<!--  the order of the next two lines is important -->
		<code function="moveReviewerFiles" />
		<code function="fixAuthorGroup" />
		<data file="dbscripts/xml/upgrade/3.0.0_reviewer_files.xml" />
		<code function="removeCancelledReviewAssignments" condition="return $installer->tableExists('review_assignments_tmp');" />
		<data file="dbscripts/xml/upgrade/3.1.0_notifications.xml" />
		<data file="dbscripts/xml/upgrade/3.1.0_notes.xml" condition="return $installer->tableExists('notes_tmp');" />
		<data file="dbscripts/xml/upgrade/3.1.0_galley_settings.xml" condition="return $installer->tableExists('article_galley_settings');" />
		<data file="dbscripts/xml/upgrade/3.1.0_update.xml" />
		<code function="repairImageAssociations" condition="return $installer->tableExists('submission_html_galley_images');" />
		<code function="installEmailTemplate" key="EDITOR_DECISION_INITIAL_DECLINE" locales="en_US,ar_IQ,cs_CZ,da_DK,de_DE,el_GR,es_ES,fa_IR,fi_FI,fr_CA,fr_FR,it_IT,nl_NL,pl_PL,pt_PT,ru_RU,sl_SI,sv_SE,tr_TR" />
		<code function="installEmailTemplate" key="EDITOR_RECOMMENDATION" locales="en_US,ar_IQ,cs_CZ,da_DK,de_DE,el_GR,es_ES,fa_IR,fi_FI,fr_CA,fr_FR,it_IT,nl_NL,pl_PL,pt_PT,ru_RU,sl_SI,sv_SE,tr_TR" />

		<note file="docs/release-notes/README-3.1.0" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.0.9">
		<data file="dbscripts/xml/upgrade/3.1.1_update.xml" />
		<code function="updateSuppFileMetrics" />
		<code function="installEmailTemplate" key="REVISED_VERSION_NOTIFY" locales="ar_IQ,da_DK,en_US,es_ES,fa_IR,fi_FI,fr_CA,fr_FR,id_ID,pt_PT,ru_RU,sv_SE" />
		<code function="clearDataCache" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.0.9">
		<code function="repairSuppFilesFilestage" />
		<code function="fixAuthorGroup" /><!-- Run again after previous invalid fix (#3289) -->
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.0.9">
		<note file="docs/release-notes/README-3.1.1" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.1.9">
		<data file="dbscripts/xml/upgrade/3.1.2_update.xml" />
		<note file="docs/release-notes/README-3.1.2" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.1.4">
		<data file="dbscripts/xml/upgrade/event_log_oneclickuserid.xml" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.1.9.9">
		<data file="dbscripts/xml/upgrade/3.2.0_stylesheet.xml" />
		<data file="dbscripts/xml/upgrade/3.2.0_archiving_settings.xml" />
		<data file="dbscripts/xml/upgrade/3.2.0_update.xml" />
		<data file="dbscripts/xml/upgrade/3.2.0_navigation_menu_items_locale_change.xml" />
		<code function="migrateSiteLocales" />
		<code function="migrateSidebarBlocks" />
		<code function="migrateSiteStylesheet" />
		<code function="migrateMetadataSettings" />
		<code function="createLicenseTerms" />
		<code function="installEmailTemplate" key="REVIEW_REINSTATE" locales="en_US" />
		<code function="changeUserRolesAndStageAssignmentsForStagePermitSubmissionEdit" />
		<data file="dbscripts/xml/upgrade/3.2.0_versioning.xml" />
		<data file="dbscripts/xml/upgrade/3.2.0_versioning_submissionCategories.xml" condition="return $installer->tableExists('submission_categories');" />
		<data file="dbscripts/xml/upgrade/3.2.0_last_activity.xml" />
		<data file="dbscripts/xml/upgrade/3.2.0_url_path.xml" />
		<code function="setStatsEmailSettings" />
		<code function="fixLibraryFiles" />
		<code function="installEmailTemplate" key="STATISTICS_REPORT_NOTIFICATION" locales="ar_IQ,ca_ES,cs_CZ,da_DK,de_DE,en_US,es_ES,fi_FI,fr_CA,hi_IN,hu_HU,id_ID,it_IT,ku_IQ,pt_BR,pt_PT,ru_RU,sl_SI,sv_SE,tr_TR,vi_VN,zh_CN" />
		<note file="docs/release-notes/README-3.2.0" />
	</upgrade>

	<upgrade minversion="3.0.0.0" maxversion="3.0.0.9">
