=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/locales.dtd
<!--
  * dtd/locales.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2000-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD for locale lists.
  -->

<!ELEMENT locales (locale+)>
<!ELEMENT locale EMPTY>
	<!ATTLIST locale
		key CDATA #REQUIRED
		name CDATA #REQUIRED
		iso639-2b CDATA #REQUIRED
		iso639-3 CDATA #REQUIRED
		complete (true | false) #IMPLIED
		stylesheet CDATA #IMPLIED
		direction CDATA #IMPLIED
		familyFirst (true | false) #IMPLIED>

=== H-Alexa/IIT-Journal-project-using-OJS/registry/locales.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  * registry/locales.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Locales registry file.
  *
  * This file lists all locales available to the system.
  * (i.e., existing under the locales/ directory)
  -->

<!DOCTYPE locales SYSTEM "../lib/pkp/dtd/locales.dtd">

<locales>
	<locale key="ar_IQ" complete="true"  name="العربية" iso639-2b="ara" iso639-3="ara" direction="rtl" />
	<locale key="bs_BA" complete="false" name="Bosanski" iso639-2b="bos" iso639-3="bos" />
	<locale key="ca_ES" complete="true" name="Català" iso639-2b="cat" iso639-3="cat" />
	<locale key="cs_CZ" complete="true" name="Čeština" iso639-2b="cze" iso639-3="ces" />
	<locale key="da_DK" complete="true" name="Dansk" iso639-2b="dan" iso639-3="dan" />
	<locale key="de_DE" complete="true"  name="Deutsch" iso639-2b="ger" iso639-3="deu" />
	<locale key="el_GR" complete="false" name="ελληνικά" iso639-2b="gre" iso639-3="ell" />
	<locale key="en_US" complete="true"  name="English" iso639-2b="eng" iso639-3="eng" />
	<locale key="es_ES" complete="true"  name="Español (España)" iso639-2b="spa" iso639-3="spa" />
	<locale key="eu_ES" complete="false" name="Euskara" iso639-2b="eus" iso639-3="eus" />
	<locale key="fa_IR" complete="true"  name="فارسی" iso639-2b="per" iso639-3="per" direction="rtl" />
	<locale key="fi_FI" complete="true" name="Suomi" iso639-2b="fin" iso639-3="fin" />
	<locale key="fr_CA" complete="true" name="Français (Canada)" iso639-2b="fre" iso639-3="fra" />
	<locale key="fr_FR" complete="true" name="Français (France)" iso639-2b="fre" iso639-3="fra" />
	<locale key="gd_GB" complete="false" name="Scottish Gaelic" iso639-2b="gla" iso639-3="gla" />
	<locale key="he_IL" complete="false" name="עברית" iso639-2b="heb" iso639-3="heb" />
	<locale key="hi_IN" complete="false" name="Hindi" iso639-2b="hin" iso639-3="hin" />
	<locale key="hu_HU" complete="true" name="Magyar" iso639-2b="hun" iso639-3="hun" />
	<locale key="hr_HR" complete="false" name="Hrvatski" iso639-2b="hrv" iso639-3="hrv" />
	<locale key="hy_AM" complete="false" name="Armenian" iso639-2b="hye" iso639-3="hye" />
	<locale key="id_ID" complete="true" name="Bahasa Indonesia" iso639-2b="ind" iso639-3="ind" />
	<locale key="it_IT" complete="true" name="Italiano" iso639-2b="ita" iso639-3="ita" />
	<locale key="ja_JP" complete="false" name="日本語" iso639-2b="jpn" iso639-3="jpn" />
	<locale key="mk_MK" complete="true" name="македонски јазик" iso639-2b="mkd" iso639-3="mkd" />
	<locale key="ko_KR" complete="false" name="한국어" iso639-2b="kor" iso639-3="kor" />
	<locale key="ku_IQ" complete="true" name="کوردی" iso639-2b="ckb" iso639-3="ckb" direction="rtl" />
	<locale key="nb_NO" complete="true" name="Norsk Bokmål" iso639-2b="nor" iso639-3="nor" />
	<locale key="nl_NL" complete="true" name="Nederlands" iso639-2b="dut" iso639-3="nld" />
	<locale key="pl_PL" complete="true" name="Język Polski" iso639-2b="pol" iso639-3="pol" />
	<locale key="pt_BR" complete="true"  name="Português (Brasil)" iso639-2b="por" iso639-3="por" />
	<locale key="pt_PT" complete="true" name="Português (Portugal)" iso639-2b="por" iso639-3="por" />
	<locale key="ro_RO" complete="true" name="Limba Română" iso639-2b="rum" iso639-3="ron" />
	<locale key="ru_RU" complete="true" name="Русский" iso639-2b="rus" iso639-3="rus" />
	<locale key="sk_SK" complete="true" name="Slovenčina" iso639-2b="slk" iso639-3="slk" />
	<locale key="sl_SI" complete="true" name="Slovenščina" iso639-2b="slv" iso639-3="slv" />
	<locale key="sr_RS@cyrillic" complete="false" name="Cрпски" iso639-2b="srp" iso639-3="srp" />
	<locale key="sr_RS@latin" complete="false" name="Srpski" iso639-2b="srp" iso639-3="srp" />
	<locale key="sv_SE" complete="true" name="Svenska" iso639-2b="swe" iso639-3="swe" />
	<locale key="tr_TR" complete="true" name="Türkçe" iso639-2b="tur" iso639-3="tur" />
	<locale key="uk_UA" complete="true" name="Українська" iso639-2b="ukr" iso639-3="ukr" />
	<locale key="vi_VN" complete="true" name="Tiếng Việt" iso639-2b="vie" iso639-3="vie" />
	<locale key="zh_CN" complete="false" name="简体中文" iso639-2b="chi" iso639-3="zho" />
</locales>
