=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/pluginVersion.dtd
<!--
  * dtd/pluginVersion.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2000-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD for plugin version data.
  *
  -->

<!ELEMENT version (application, type, release, tag?, date, lazy-load?, sitewide?, class?)>
<!ELEMENT application (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT release (#PCDATA)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT lazy-load (#PCDATA)>
<!ELEMENT sitewide (#PCDATA)>
<!ELEMENT class (#PCDATA)>

=== H-Alexa/IIT-Journal-project-using-OJS/plugins/generic/recommendByAuthor/version.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE version SYSTEM "../../../lib/pkp/dtd/pluginVersion.dtd">

<!--
  * plugins/generic/recommendByAuthor/version.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Plugin version information.
  -->
<version>
	<application>recommendByAuthor</application>
	<type>plugins.generic</type>
	<release>1.0.0.0</release>
	<date>2013-04-30</date>
	<lazy-load>1</lazy-load>
	<sitewide>1</sitewide>
	<class>RecommendByAuthorPlugin</class>
</version>

=== H-Alexa/IIT-Journal-project-using-OJS/plugins/generic/acron/version.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE version SYSTEM "../../../lib/pkp/dtd/pluginVersion.dtd">

<!--
  * plugins/generic/acron/version.xml
  *
  * Copyright (c) 2013-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Plugin version information.
  -->
<version>
	<application>acron</application>
	<type>plugins.generic</type>
	<release>1.2.0.0</release>
	<date>2016-08-10</date>
	<lazy-load>1</lazy-load>
	<sitewide>1</sitewide>
	<class>AcronPlugin</class>
</version>
