=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/pluginSettings.dtd
<!--
  * dtd/pluginSettings.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2000-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD for installing plugin settings.
  *
  -->

<!ELEMENT plugin_settings (setting+)>
<!ELEMENT setting (name, value)>
<!ATTLIST setting type (int|string|object|bool) #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA | array)*>
<!ELEMENT element (#PCDATA | array)*>
<!ATTLIST element key CDATA #IMPLIED>
<!ELEMENT array (element+)>

=== H-Alexa/IIT-Journal-project-using-OJS/plugins/generic/webFeed/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin_settings SYSTEM "../../../lib/pkp/dtd/pluginSettings.dtd">

<!--
  * plugins/generic/webFeed/settings.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Default plugin settings.
  *
  -->

<plugin_settings>
	<setting type="bool">
		<name>enabled</name>
		<value>true</value>
	</setting>
	<setting type="string">
		<name>displayPage</name>
		<value>homepage</value>
	</setting>
	<setting type="bool">
		<name>displayItems</name>
		<value>issue</value>
	</setting>
</plugin_settings>

=== H-Alexa/IIT-Journal-project-using-OJS/plugins/generic/usageStats/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin_settings SYSTEM "../../../lib/pkp/dtd/pluginSettings.dtd">

<!--
  * plugins/generic/usageStats/settings.xml
  *
  * Copyright (c) 2013-2020 Simon Fraser University
  * Copyright (c) 2003-2020 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Default plugin settings.
  *
  -->

<plugin_settings>
	<setting type="bool">
		<name>enabled</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>createLogFiles</name>
		<value>true</value>
	</setting>
	<setting type="string">
		<name>accessLogFileParseRegex</name>
		<value>/^(?P&lt;ip&gt;\S+) \S+ \S+ \[(?P&lt;date&gt;.*?)\] "\S+ (?P&lt;url&gt;\S+).*?" (?P&lt;returnCode&gt;\S+) \S+ ".*?" "(?P&lt;userAgent&gt;.*?)"/</value>
	</setting>
	<setting type="object">
		<name>optionalColumns</name>
		<value>
			<array>
				<element>city</element>
				<element>region</element>
			</array>
		</value>
	</setting>
	<setting type="string">
		<name>chartType</name>
		<value>bar</value>
	</setting>
	<setting type="string">
		<name>datasetMaxCount</name>
		<value>4</value>
	</setting>
</plugin_settings>
