=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/userGroups.dtd
<!--
  * dtd/userGroups.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2000-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD for default user group settings.
  *
  -->
<!ELEMENT groups (group+)>
<!ELEMENT group EMPTY>
	<!ATTLIST group
		roleId CDATA #REQUIRED
		stages CDATA #IMPLIED
		name CDATA #REQUIRED
		plural CDATA #REQUIRED
		abbrev CDATA #REQUIRED
		permitSelfRegistration CDATA #IMPLIED
		permitMetadataEdit CDATA #IMPLIED>

=== H-Alexa/IIT-Journal-project-using-OJS/registry/userGroups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE groups SYSTEM "../lib/pkp/dtd/userGroups.dtd">

<!--
  * registry/userGroups.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Roles XML file.
  *
  -->

<groups>
	<!-- Managerial Role -->
	<group roleId="0x00000010" name="default.groups.name.manager" plural="default.groups.plural.manager" abbrev="default.groups.abbrev.manager" permitMetadataEdit="true" />
	<group roleId="0x00000010" stages="1,3,4,5" name="default.groups.name.editor" plural="default.groups.plural.editor" abbrev="default.groups.abbrev.editor" permitMetadataEdit="true" />
	<group roleId="0x00000010" stages="4,5" name="default.groups.name.productionEditor" plural="default.groups.plural.productionEditor" abbrev="default.groups.abbrev.productionEditor" permitMetadataEdit="true" />

	<!--  Section Editor Role -->
	<group roleId="0x00000011" stages="1,3,4,5" name="default.groups.name.sectionEditor" plural="default.groups.plural.sectionEditor" abbrev="default.groups.abbrev.sectionEditor" permitMetadataEdit="true" />

	<!-- Guest editor role -->
	<group roleId="0x00000011" stages="1,3,4,5" name="default.groups.name.guestEditor" plural="default.groups.plural.guestEditor" abbrev="default.groups.abbrev.guestEditor" />

	<!-- Journal Role -->
	<group roleId="0x00001001" stages="4" name="default.groups.name.copyeditor" plural="default.groups.plural.copyeditor" abbrev="default.groups.abbrev.copyeditor" />
	<group roleId="0x00001001" stages="5" name="default.groups.name.designer" plural="default.groups.plural.designer" abbrev="default.groups.abbrev.designer" />
	<group roleId="0x00001001" stages="1,3" name="default.groups.name.funding" plural="default.groups.plural.funding" abbrev="default.groups.abbrev.funding" />
	<group roleId="0x00001001" stages="5" name="default.groups.name.indexer" plural="default.groups.plural.indexer" abbrev="default.groups.abbrev.indexer" />
	<group roleId="0x00001001" stages="5" name="default.groups.name.layoutEditor" plural="default.groups.plural.layoutEditor" abbrev="default.groups.abbrev.layoutEditor" />
	<group roleId="0x00001001" stages="4" name="default.groups.name.marketing" plural="default.groups.plural.marketing" abbrev="default.groups.abbrev.marketing" />
	<group roleId="0x00001001" stages="5" name="default.groups.name.proofreader" plural="default.groups.plural.proofreader" abbrev="default.groups.abbrev.proofreader" />

	<!-- Author Role -->
	<group roleId="0x00010000" stages="1,3,4,5" name="default.groups.name.author" plural="default.groups.plural.author" abbrev="default.groups.abbrev.author" permitSelfRegistration="true" />
	<group roleId="0x00010000" stages="1,3,4,5" name="default.groups.name.translator" plural="default.groups.plural.translator" abbrev="default.groups.abbrev.translator" />

	<!-- Reviewer Role -->
	<group roleId="0x00001000" stages="3" name="default.groups.name.externalReviewer" plural="default.groups.plural.externalReviewer" abbrev="default.groups.abbrev.externalReviewer" permitSelfRegistration="true" />

	<!-- Reader Role -->
	<group roleId="0x00100000" stages="" name="default.groups.name.reader" plural="default.groups.plural.reader" abbrev="default.groups.abbrev.reader" permitSelfRegistration="true" />

	<!-- Subscription Manager Role -->
	<group roleId="0x00200000" stages="" name="default.groups.name.subscriptionManager" plural="default.groups.plural.subscriptionManager" abbrev="default.groups.abbrev.subscriptionManager" />
</groups>
