=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/version.dtd
<!--
  * dtd/version.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2000-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD describing PKP application version information.
  *
  -->

<!ELEMENT version (application, type, release, tag, date, info, package, patch*)>
<!ELEMENT application (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT release (#PCDATA)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT package (#PCDATA)>
<!ELEMENT patch (#PCDATA)>
	<!ATTLIST patch
		from CDATA #REQUIRED>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/version.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE version SYSTEM "../../lib/pkp/dtd/version.dtd">
<!--
  * dbscripts/xml/version.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * OJS version information.
  -->

<version>
	<application>ojs2</application>
	<type>core</type>
	<release>3.3.0.7</release>
	<tag>3_3_0-7</tag>
	<date>2021-06-23</date>
	<info>http://pkp.sfu.ca/ojs/</info>
	<package>http://pkp.sfu.ca/ojs/download/ojs-3.3.0-7.tar.gz</package>
</version>
