=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/xmlData.dtd
<!--
  * dtd/xmlData.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2014-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD describing database data and/or operations.
  -->

<!ELEMENT data (table?, sql?)*>

<!-- Table data -->
<!ELEMENT table (row*)+>
	<!ATTLIST table
		name CDATA #REQUIRED>
<!ELEMENT row (field+)>
<!ELEMENT field (#PCDATA)>
	<!ATTLIST field
		name CDATA #REQUIRED
		null (0|1) #IMPLIED>

<!-- Raw SQL -->
<!ELEMENT sql (query|drop|dropindex|rename)*>
<!ELEMENT query (#PCDATA)>
	<!-- The "driver" attribute can specify several drivers using comma separators. -->
	<!ATTLIST query
		driver CDATA #IMPLIED>

<!-- Schema operations -->
<!ELEMENT drop EMPTY>
	<!ATTLIST drop
		table CDATA #REQUIRED
		column CDATA #IMPLIED>
<!ELEMENT dropindex EMPTY>
	<!ATTLIST dropindex
		table CDATA #REQUIRED
		index CDATA #REQUIRED
		ifexists CDATA #IMPLIED>
<!ELEMENT rename EMPTY>
	<!ATTLIST rename
		table CDATA #REQUIRED
		column CDATA #IMPLIED
		to CDATA #REQUIRED>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
 * dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml
 *
 * Copyright (c) 2013-2021 Simon Fraser University
 * Copyright (c) 2003-2021 John Willinsky
 * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
 *
 * Copy submission data to temporary tables so it can be updated
 * after the publication table modifications are made.
 *
 -->

<data>
	<sql>
		<query>CREATE TABLE temp_authors AS SELECT * FROM authors</query>
		<query>CREATE INDEX temp_authors_s_id ON temp_authors (submission_id)</query>
		<query>CREATE INDEX temp_authors_a_s_id ON temp_authors (author_id, submission_id)</query>
		<query>CREATE TABLE temp_submissions AS SELECT * FROM submissions</query>
		<query>CREATE INDEX temp_submissions_s_id ON temp_submissions (submission_id)</query>
		<query>CREATE TABLE temp_submission_galleys AS SELECT * FROM submission_galleys</query>
		<query>CREATE INDEX temp_submission_galleys_s_id ON temp_submission_galleys (submission_id)</query>
		<query>CREATE TABLE temp_published_submissions AS SELECT * FROM published_submissions</query>
		<query>CREATE INDEX temp_published_submissions_s_id ON temp_published_submissions (submission_id)</query>
		<query>CREATE TABLE temp_citations AS SELECT * FROM citations</query>
		<query>CREATE INDEX temp_citations_s_id ON temp_citations (submission_id)</query>
		<query>CREATE INDEX temp_citations_c_s_id ON temp_citations (citation_id, submission_id)</query>
	</sql>
	<!--
		Identify any submissions with STATUS_PUBLISHED that are missing a corresponding entry
		in the published_submissions table and reset them to STATUS_QUEUED. In the past, an
		entry in published_submissions was required before a submission would be public. Now
		it will be public if it has a status of STATUS_PUBLISHED. A submission should never
		have STATUS_PUBLISHED without a published_submissions entry, but this is a
		precautionary measure to prevent unexpectedly making a submission public if the
		status value is incorrect for any submissions.
	-->
	<sql>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE submissions SET status=1 FROM submissions AS s LEFT JOIN published_submissions ps ON (ps.submission_id = s.submission_id) WHERE s.submission_id = submissions.submission_id AND s.status=3 AND ps.submission_id IS NULL</query>
		<query driver="mysql,mysqli">UPDATE submissions s LEFT JOIN published_submissions ps ON (ps.submission_id = s.submission_id) SET s.status=1 WHERE s.status=3 AND ps.submission_id IS NULL</query>
	</sql>
	<!-- Modify citations table to refer to publications #5465-->
	<sql>
		<dropindex table="citations" index="citations_submission" ifexists="true" />
		<dropindex table="citations" index="citations_submission_seq" ifexists="true" />
		<rename table="citations" column="submission_id" to="publication_id" />
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.1.0_update_a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * 3.1.0_update_a.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * 3.1.0.0 general updates only for installations using 3.x.
  -->
<data>
	<sql>
		<!-- issue #2506: repair migrated files genre ids -->
		<query driver="mysql,mysqli">UPDATE submission_files sf, genres g, submissions s SET sf.genre_id = g.genre_id WHERE sf.genre_id = 1 AND g.entry_key = 'SUBMISSION' AND g.context_id = s.context_id AND s.submission_id = sf.submission_id</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE submission_files SET genre_id = g.genre_id FROM genres g, submissions s WHERE submission_files.genre_id = 1 AND g.entry_key = 'SUBMISSION' AND g.context_id = s.context_id AND s.submission_id = submission_files.submission_id</query>
	</sql>
	<sql><!-- pkp/pkp-lib#2543 -->
		<query>UPDATE filter_groups SET input_type = 'class::classes.submission.Submission' WHERE symbolic = 'article=>doaj-json'</query>
	</sql>
	<sql><!-- pkp/pkp-lib#2896 -->
		<query>UPDATE journal_settings SET setting_name = 'citationsEnabledSubmission' WHERE setting_name = 'referencesEnabledSubmission'</query>
		<query>UPDATE journal_settings SET setting_name = 'citationsEnabledWorkflow' WHERE setting_name = 'referencesEnabledWorkflow'</query>
		<query>UPDATE journal_settings SET setting_name = 'citationsRequired' WHERE setting_name = 'referencesRequired'</query>
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.2.0_update.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * 3.2.0_update.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * 3.2.0.0 general updates.
  -->
<data>
	<sql><!-- pkp/pkp-lib#2160/4726: Clean up editorial history -->
		<query>UPDATE event_log_settings SET setting_name='submissionId' WHERE setting_name='articleId'</query>
		<query>UPDATE event_log_settings SET setting_name='submissionId' WHERE setting_name='submission_id'</query>
	</sql>
	<sql><!-- pkp/pkp-lib#4573 Enable OAI interface by default -->
		<!-- PostgreSQL ADODB driver does not seem to properly support dropping constraints -->
		<query driver="postgres7">ALTER TABLE journal_settings ALTER COLUMN setting_type DROP NOT NULL</query>
		<query>INSERT INTO journal_settings (setting_name, setting_value, journal_id) SELECT 'enableOai', '1', j.journal_id FROM journals j WHERE NOT EXISTS (SELECT js.setting_name FROM journal_settings js WHERE js.setting_name = 'enableOai' AND js.journal_id = j.journal_id)</query>
	</sql>
	<sql><!-- pkp/pkp-lib#5445 Use new setting name for LicenseUrl -->
		<query>UPDATE journal_settings SET setting_name='licenseUrl' WHERE setting_name='licenseURL'</query>
		<query>UPDATE publication_settings SET setting_name='licenseUrl' WHERE setting_name='licenseURL'</query>
	</sql>
	<sql><!-- Migrate immersion theme settings stored as context settings to plugin settings -->
		<query>
			INSERT INTO plugin_settings (plugin_name, context_id, setting_name, setting_value, setting_type)
				SELECT 'immersionthemeplugin', js.journal_id, js.setting_name, js.setting_value, 'string'
				FROM journal_settings as js
				WHERE js.setting_name='immersionAnnouncementsColor'
		</query>
		<query>
			DELETE FROM journal_settings WHERE setting_name='immersionAnnouncementsColor'
		</query>
	</sql>
	<!-- Migrate email templates from email_templates_data to email_templates_settings -->
	<sql>
		<query>
			INSERT INTO email_templates_settings (email_id, locale, setting_value, setting_name)
			SELECT email_id, locale, subject, 'subject'
			FROM email_templates_data
		</query>
		<query>
			INSERT INTO email_templates_settings (email_id, locale, setting_value, setting_name)
			SELECT email_id, locale, body, 'body'
			FROM email_templates_data
		</query>
		<drop table="email_templates_data" />
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.1.1_update.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * 3.1.1_update.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * 3.1.1.0 general updates.
  -->
<data>
	<sql><!-- pkp/pkp-lib#2441 rename masthead to editorialTeam in journal_settings -->
		<query>UPDATE journal_settings SET setting_name = 'editorialTeam' WHERE setting_name = 'masthead'</query>
	</sql>
	<sql>
		<!-- issue #2874: remove citationLookup, citationParser and nlm30 metadata plugin -->
		<!-- remove filter_settings -->
		<query driver="mysql,mysqli">DELETE FROM fs USING filter_settings fs INNER JOIN filters f ON (fs.filter_id = f.filter_id) INNER JOIN filter_groups fg ON (f.filter_group_id = fg.filter_group_id AND fg.symbolic IN ('citation=>nlm30', 'isbn=>nlm30-element-citation', 'nlm30-article-xml=>nlm23-article-xml', 'nlm30-element-citation=>isbn', 'nlm30-element-citation=>nlm30-element-citation', 'nlm30-element-citation=>nlm30-xml', 'nlm30-element-citation=>plaintext', 'nlm30=>citation', 'plaintext=>nlm30-element-citation', 'submission=>nlm23-article-xml', 'submission=>nlm30-article-xml', 'submission=>reference-list'))</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">DELETE FROM filter_settings fs USING filters f, filter_groups fg WHERE fs.filter_id = f.filter_id AND f.filter_group_id = fg.filter_group_id AND fg.symbolic IN ('citation=>nlm30', 'isbn=>nlm30-element-citation', 'nlm30-article-xml=>nlm23-article-xml', 'nlm30-element-citation=>isbn', 'nlm30-element-citation=>nlm30-element-citation', 'nlm30-element-citation=>nlm30-xml', 'nlm30-element-citation=>plaintext', 'nlm30=>citation', 'plaintext=>nlm30-element-citation', 'submission=>nlm23-article-xml', 'submission=>nlm30-article-xml', 'submission=>reference-list')</query>
		<!-- remove filters -->
		<query driver="mysql,mysqli">DELETE FROM f USING filters f INNER JOIN filter_groups fg ON (f.filter_group_id = fg.filter_group_id AND fg.symbolic IN ('citation=>nlm30', 'isbn=>nlm30-element-citation', 'nlm30-article-xml=>nlm23-article-xml', 'nlm30-element-citation=>isbn', 'nlm30-element-citation=>nlm30-element-citation', 'nlm30-element-citation=>nlm30-xml', 'nlm30-element-citation=>plaintext', 'nlm30=>citation', 'plaintext=>nlm30-element-citation', 'submission=>nlm23-article-xml', 'submission=>nlm30-article-xml', 'submission=>reference-list'))</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">DELETE FROM filters f USING filter_groups fg WHERE f.filter_group_id = fg.filter_group_id AND fg.symbolic IN ('citation=>nlm30', 'isbn=>nlm30-element-citation', 'nlm30-article-xml=>nlm23-article-xml', 'nlm30-element-citation=>isbn', 'nlm30-element-citation=>nlm30-element-citation', 'nlm30-element-citation=>nlm30-xml', 'nlm30-element-citation=>plaintext', 'nlm30=>citation', 'plaintext=>nlm30-element-citation', 'submission=>nlm23-article-xml', 'submission=>nlm30-article-xml', 'submission=>reference-list')</query>
		<!-- remove filter_groups -->
		<query>DELETE FROM filter_groups WHERE symbolic IN ('citation=>nlm30', 'isbn=>nlm30-element-citation', 'nlm30-article-xml=>nlm23-article-xml', 'nlm30-element-citation=>isbn', 'nlm30-element-citation=>nlm30-element-citation', 'nlm30-element-citation=>nlm30-xml', 'nlm30-element-citation=>plaintext', 'nlm30=>citation', 'plaintext=>nlm30-element-citation', 'submission=>nlm23-article-xml', 'submission=>nlm30-article-xml', 'submission=>reference-list')</query>
	</sql>
	<sql><!-- pkp/pkp-lib#3311 rename subject(EnabledSubmission, EnabledWorkflow, Required) to subjects(EnabledSubmission, EnabledWorkflow, Required) in journal_settings -->
		<query>UPDATE journal_settings SET setting_name = 'subjectsEnabledSubmission' WHERE setting_name = 'subjectEnabledSubmission'</query>
		<query>UPDATE journal_settings SET setting_name = 'subjectsEnabledWorkflow' WHERE setting_name = 'subjectEnabledWorkflow'</query>
		<query>UPDATE journal_settings SET setting_name = 'subjectsRequired' WHERE setting_name = 'subjectRequired'</query>
	</sql>
	<!-- pkp/pkp-lib#2894 Set 0 review ratings to NULL -->
	<sql>
		<query>UPDATE review_assignments SET quality = NULL WHERE quality = 0</query>
	</sql>
	<!-- pkp/pkp-lib#2894 Update old localised user gossip entries -->
	<sql>
		<query driver="mysql,mysqli">UPDATE users u, (SELECT user_id, GROUP_CONCAT(DISTINCT setting_value SEPARATOR ' ') AS groupedGossips FROM user_settings WHERE setting_name = 'gossip' AND setting_value &lt;&gt; '' GROUP BY user_id) us SET u.gossip = us.groupedGossips WHERE us.user_id = u.user_id</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE users SET gossip = us.groupedGossips FROM (SELECT user_id, string_agg(DISTINCT setting_value, ' ') AS groupedGossips FROM user_settings WHERE setting_name = 'gossip' AND setting_value &lt;&gt; '' GROUP BY user_id) AS us WHERE us.user_id = users.user_id</query>
		<query>DELETE FROM user_settings WHERE setting_name='gossip'</query>
	</sql>
	<sql><!-- pkp/pkp-lib#3412 Clean up notifications left over from deleted announcements -->
		<query driver="mysql,mysqli">DELETE n FROM notifications n LEFT JOIN announcements a ON (n.assoc_id = a.announcement_id) WHERE a.announcement_id IS NULL AND n.assoc_type = 522</query><!-- ASSOC_TYPE_ANNOUNCEMENT -->
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">DELETE FROM notifications USING notifications n LEFT JOIN announcements a ON (n.assoc_id = a.announcement_id) WHERE a.announcement_id IS NULL AND n.assoc_type = 522 AND notifications.notification_id = n.notification_id</query><!-- ASSOC_TYPE_ANNOUNCEMENT -->
	</sql>
	<sql><!-- pkp/pkp-lib#3694 migrate DataCite, mEDRA and DOAJ registered status -->
		<!--  we cannot differentiate if the registration was done via API or manually in OJS 2, thus we will use status = registered (as the API was eused) and not markedRegistered -->
		<!-- DataCite -->
		<query>INSERT INTO issue_settings (issue_id, setting_name, setting_value, setting_type) SELECT issue_id, 'datacite::status', 'registered', 'string' FROM issue_settings WHERE setting_name = 'datacite::registeredDoi' AND (setting_value IS NOT NULL OR setting_value &lt;&gt; '') AND issue_id NOT IN (SELECT issue_id FROM issue_settings WHERE setting_name = 'datacite::status')</query>
		<query>INSERT INTO submission_settings (submission_id, setting_name, setting_value) SELECT submission_id, 'datacite::status', 'registered' FROM submission_settings WHERE setting_name = 'datacite::registeredDoi' AND (setting_value IS NOT NULL OR setting_value &lt;&gt; '') AND submission_id NOT IN (SELECT submission_id FROM submission_settings WHERE setting_name = 'datacite::status')</query>
		<query>INSERT INTO submission_galley_settings (galley_id, setting_name, setting_value, setting_type) SELECT galley_id, 'datacite::status', 'registered', 'string' FROM submission_galley_settings WHERE setting_name = 'datacite::registeredDoi' AND (setting_value IS NOT NULL OR setting_value &lt;&gt; '') AND galley_id NOT IN (SELECT galley_id FROM submission_galley_settings WHERE setting_name = 'datacite::status')</query>
		<!-- mEDRA -->
		<query>INSERT INTO issue_settings (issue_id, setting_name, setting_value, setting_type) SELECT issue_id, 'medra::status', 'registered', 'string' FROM issue_settings WHERE setting_name = 'medra::registeredDoi' AND (setting_value IS NOT NULL OR setting_value &lt;&gt; '') AND issue_id NOT IN (SELECT issue_id FROM issue_settings WHERE setting_name = 'medra::status')</query>
		<query>INSERT INTO submission_settings (submission_id, setting_name, setting_value) SELECT submission_id, 'medra::status', 'registered' FROM submission_settings WHERE setting_name = 'medra::registeredDoi' AND (setting_value IS NOT NULL OR setting_value &lt;&gt; '') AND submission_id NOT IN (SELECT submission_id FROM submission_settings WHERE setting_name = 'medra::status')</query>
		<query>INSERT INTO submission_galley_settings (galley_id, setting_name, setting_value, setting_type) SELECT galley_id, 'medra::status', 'registered', 'string' FROM submission_galley_settings WHERE setting_name = 'medra::registeredDoi' AND (setting_value IS NOT NULL OR setting_value &lt;&gt; '') AND galley_id NOT IN (SELECT galley_id FROM submission_galley_settings WHERE setting_name = 'medra::status')</query>
		<!-- DOAJ -->
		<!-- there was no DOAJ API integration in OJS 2, thus only the manuall registration was possible, so we will use status = markedRegistered -->
		<query>INSERT INTO submission_settings (submission_id, setting_name, setting_value) SELECT submission_id, 'doaj::status', 'markedRegistered' FROM submission_settings WHERE setting_name = 'doaj::registered' AND (setting_value IS NOT NULL OR setting_value &lt;&gt; '') AND submission_id NOT IN (SELECT submission_id FROM submission_settings WHERE setting_name = 'doaj::status')</query>
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.0.0_preupdate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * 3.0.0_preupdate.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Database updates XML file (run before schema is reconciled).
  *
  -->
<data>
	<!-- Bug #8744: Abstract series/section editor assignments -->
	<sql>
		<rename table="section_editors" column="journal_id" to="context_id" />
	</sql>
	<!-- Bug #8265: Rename plugin_settings.journal_id to context_id -->
	<sql>
		<rename table="plugin_settings" column="journal_id" to="context_id" />
	</sql>
	<!-- Bug #8148: Submission process into PKP lib -->
	<sql>
		<rename table="edit_decisions" column="article_id" to="submission_id" />
	</sql>
	<sql>
		<rename table="static_pages" column="journal_id" to="context_id" />
	</sql>

	<!-- Articles migration -->
	<sql>
		<query>CREATE TABLE articles_migration AS (SELECT journal_id, article_id, user_id, submission_file_id, revised_file_id, review_file_id, editor_file_id, language FROM articles)</query>
	</sql>

	<!-- Article files migration -->
	<sql>
		<query>CREATE TABLE article_files_migration AS (SELECT * FROM article_files)</query>
	</sql>

	<!-- Article HTML galley CSS file migration -->
	<sql>
		<query>CREATE TABLE article_galleys_migration AS (SELECT galley_id, file_id, style_file_id FROM article_galleys)</query>
	</sql>

	<!-- Bug #8235: Rename article* submission* -->
	<sql>
		<!-- article_files to submission_files -->
		<rename table="article_files" column="article_id" to="submission_id" />
		<rename table="article_files" to="submission_files" />
		<!-- article_comments to submission_comments -->
		<rename table="article_comments" column="article_id" to="submission_id" />
		<rename table="article_comments" to="submission_comments" />
		<!-- articles to submissions -->
		<rename table="articles" column="article_id" to="submission_id" />
		<rename table="articles" column="journal_id" to="context_id" />
		<rename table="articles" to="submissions" />
		<!-- article_galleys to submission_galleys -->
		<rename table="article_galleys" column="article_id" to="submission_id" />
		<rename table="article_galleys" to="submission_galleys" />
		<!-- article_search_objects to submission_search_objects -->
		<rename table="article_search_objects" column="article_id" to="submission_id" />
		<rename table="article_search_objects" to="submission_search_objects" />
		<!-- article_settings to submission_settings -->
		<rename table="article_settings" column="article_id" to="submission_id" />
		<rename table="article_settings" to="submission_settings" />
		<!-- published_articles to published_submissions -->
		<rename table="published_articles" column="article_id" to="submission_id" />
		<rename table="published_articles" column="published_article_id" to="published_submission_id" />
		<rename table="published_articles" to="published_submissions" />
		<!-- article_xml_galleys to submission_xml_galleys -->
		<rename table="article_xml_galleys" column="article_id" to="submission_id" />
		<rename table="article_xml_galleys" to="submission_xml_galleys" />

		<!-- various table renames -->
		<rename table="article_search_keyword_list" to="submission_search_keyword_list" />
		<rename table="article_search_object_keywords" to="submission_search_object_keywords" />
		<rename table="article_html_galley_images" to="submission_html_galley_images" />
	</sql>
	<!-- Clean up after OJS 2.4.x hard-coded controlled vocab / controlled vocab entry IDs (issue #1793) -->
	<sql>
		<query driver="postgres7">SELECT pg_catalog.setval(pg_get_serial_sequence('controlled_vocabs', 'controlled_vocab_id'), (SELECT MAX(controlled_vocab_id) FROM controlled_vocabs)+1)</query>
		<query driver="postgres7">SELECT pg_catalog.setval(pg_get_serial_sequence('controlled_vocab_entries', 'controlled_vocab_entry_id'), (SELECT MAX(controlled_vocab_entry_id) FROM controlled_vocab_entries)+1)</query>
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.0.0_change_assoc_type.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * dbscripts/xml/upgrade/3.0.0_change_assoc_type.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * 3.0.0.0 updates for assoc_type XML file.
  -->
<data>
	<!-- synchronize the ASSOC_TYPE_ARTICLE constant to ASSOC_TYPE_SUBMISSION defined in PKPApplication -->
	<sql>
		<query>UPDATE controlled_vocabs SET assoc_type = 1048585 WHERE assoc_type = 257</query>
		<query>UPDATE notifications SET assoc_type = 1048585 WHERE assoc_type = 257</query>
		<query>UPDATE notes SET assoc_type = 1048585 WHERE assoc_type = 257</query>
		<query>UPDATE email_log SET assoc_type = 1048585 WHERE assoc_type = 257</query>
		<query>UPDATE event_log SET assoc_type = 1048585 WHERE assoc_type = 257</query>
		<query>UPDATE signoffs SET assoc_type = 1048585 WHERE assoc_type = 257</query>
	</sql>
	<!-- synchronize the ASSOC_TYPE_GALLEY constant to ASSOC_TYPE_REPRESENTATION defined in PKPApplication -->
	<sql>
		<query>UPDATE controlled_vocabs SET assoc_type = 521 WHERE assoc_type = 260</query>
		<query>UPDATE notifications SET assoc_type = 521 WHERE assoc_type = 260</query>
		<query>UPDATE notes SET assoc_type = 521 WHERE assoc_type = 260</query>
		<query>UPDATE submission_files SET assoc_type = 521 WHERE assoc_type = 260</query>
		<query>UPDATE email_log SET assoc_type = 521 WHERE assoc_type = 260</query>
		<query>UPDATE event_log SET assoc_type = 521 WHERE assoc_type = 260</query>
		<query>UPDATE signoffs SET assoc_type = 521 WHERE assoc_type = 260</query>
	</sql>
	<!-- synchronize the ASSOC_TYPE_ANNOUNCEMENT constant change -->
	<sql>
		<query>UPDATE notifications SET assoc_type = 522 WHERE assoc_type = 258</query>
	</sql>
	<!-- synchronize the NOTIFICATION_TYPE_REVIEWER_COMMENT constant change -->
	<sql>
		<query>UPDATE notifications SET type=16777219 WHERE type=16777233</query>
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
 * dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml
 *
 * Copyright (c) 2013-2021 Simon Fraser University
 * Copyright (c) 2003-2021 John Willinsky
 * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
 *
 * Update the email templates tables to remove unused columns, add a new
 * email_id column and primary key, and update outdated role ids for the
 * default templates.
 *
 -->

<data>
	<sql><!-- pkp/pkp-lib#4988 Fix obsolete submissionLayoutUrl email variable -->
                <query>UPDATE email_templates_default_data SET body=REPLACE(body, '{$submissionLayoutUrl}', '{$submissionUrl}')</query>
                <query>UPDATE email_templates_data SET body=REPLACE(body, '{$submissionLayoutUrl}', '{$submissionUrl}')</query>
	</sql>
	<sql><!-- pkp/pkp-lib#3248 Correct duplication of email signatures -->
		<query>UPDATE email_templates_default_data SET body=REPLACE(body, '{$editorialContactSignature}', '') WHERE email_key IN ('EDITOR_ASSIGN', 'REVIEW_CANCEL', 'REVIEW_ACK', 'EDITOR_DECISION_ACCEPT', 'EDITOR_DECISION_SEND_TO_EXTERNAL', 'EDITOR_DECISION_SEND_TO_PRODUCTION', 'EDITOR_DECISION_REVISIONS', 'EDITOR_DECISION_RESUBMIT', 'EDITOR_DECISION_DECLINE', 'EDITOR_DECISION_INITIAL_DECLINE', 'EDITOR_RECOMMENDATION', 'COPYEDIT_REQUEST', 'LAYOUT_REQUEST', 'PROOFREAD_LAYOUT_REQUEST')</query>
		<query>UPDATE email_templates_data SET body=REPLACE(body, '{$editorialContactSignature}', '') WHERE email_key IN ('EDITOR_ASSIGN', 'REVIEW_CANCEL', 'REVIEW_ACK', 'EDITOR_DECISION_ACCEPT', 'EDITOR_DECISION_SEND_TO_EXTERNAL', 'EDITOR_DECISION_SEND_TO_PRODUCTION', 'EDITOR_DECISION_REVISIONS', 'EDITOR_DECISION_RESUBMIT', 'EDITOR_DECISION_DECLINE', 'EDITOR_DECISION_INITIAL_DECLINE', 'EDITOR_RECOMMENDATION', 'COPYEDIT_REQUEST', 'LAYOUT_REQUEST', 'PROOFREAD_LAYOUT_REQUEST')</query>
	</sql>
	<sql>
		<query>ALTER TABLE email_templates_data ADD email_id BIGINT</query>

		<query driver="mysql,mysqli">UPDATE email_templates_data etd LEFT JOIN email_templates et ON (etd.email_key = et.email_key AND etd.assoc_type = et.assoc_type AND etd.assoc_id = et.assoc_id) SET etd.email_id = et.email_id</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE email_templates_data SET email_id=email_templates.email_id FROM email_templates WHERE email_templates_data.email_key = email_templates.email_key AND email_templates_data.assoc_type = email_templates.assoc_type AND email_templates_data.assoc_id = email_templates.assoc_id</query>

		<query>ALTER TABLE email_templates ADD context_id BIGINT</query>
		<query>UPDATE email_templates SET context_id = assoc_id WHERE assoc_type=256 AND assoc_id IS NOT NULL</query>
		<dropindex table="email_templates" index="email_templates_assoc" />
		<dropindex table="email_templates" index="email_templates_email_key" />
		<query>ALTER TABLE email_templates DROP COLUMN assoc_type, DROP COLUMN assoc_id</query>
		<!-- 16 = ROLE_ID_MANAGER, 17 = ROLE_ID_SUB_EDITOR, 256 and 512 = unused role ids -->
		<query>UPDATE email_templates_default SET from_role_id=16 WHERE from_role_id=17 OR from_role_id=256 OR from_role_id=512</query>
		<!-- 16 = ROLE_ID_MANAGER, 17 = ROLE_ID_SUB_EDITOR, 256 and 512 = unused role ids -->
		<query>UPDATE email_templates_default SET to_role_id=16 WHERE to_role_id=17 OR to_role_id=256 OR to_role_id=512</query>
		<!-- 4097 = ROLE_ID_ASSISTANT, 768 and 8192 = unused role ids -->
		<query>UPDATE email_templates_default SET from_role_id=4097 WHERE from_role_id=768 OR from_role_id=8192</query>
		<!-- 4097 = ROLE_ID_ASSISTANT, 768 and 8192 = unused role ids -->
		<query>UPDATE email_templates_default SET to_role_id=4097 WHERE to_role_id=768 OR to_role_id=8192</query>
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.2.1_update.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * dbscripts/xml/upgrade/3.2.1_update.xml
  *
  * Copyright (c) 2013-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * Update queries for OJS 3.2.1.
  -->

<data>
	<sql><!-- pkp/pkp-lib#5617 Make all theme plugins lazy load plugins -->
		<query>UPDATE versions SET lazy_load = 1 WHERE product_type = 'plugins.themes'</query>
	</sql>
	<sql><!-- pkp/pkp-lib#5573: Filters need updating for shift to Submissions instead of Articles -->
		<query>UPDATE filter_groups SET input_type = 'class::classes.submission.Submission' WHERE input_type = 'class::classes.article.Article'</query>
		<query>UPDATE filter_groups SET output_type = 'class::classes.submission.Submission' WHERE output_type = 'class::classes.article.Article'</query>
	</sql>
	<sql><!-- pkp/pkp-lib#5681: Filters need updating for shift to Submissions instead of Articles -->
		<query>UPDATE filter_groups SET input_type = 'class::classes.submission.Submission[]' WHERE input_type = 'class::classes.article.Article[]'</query>
		<query>UPDATE filter_groups SET output_type = 'class::classes.submission.Submission[]' WHERE output_type = 'class::classes.article.Article[]'</query>
	</sql>
</data>
