=== H-Alexa/IIT-Journal-project-using-OJS/lib/pkp/dtd/xmlData.dtd
<!--
  * dtd/xmlData.dtd
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2014-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD describing database data and/or operations.
  -->

<!ELEMENT data (table?, sql?)*>

<!-- Table data -->
<!ELEMENT table (row*)+>
	<!ATTLIST table
		name CDATA #REQUIRED>
<!ELEMENT row (field+)>
<!ELEMENT field (#PCDATA)>
	<!ATTLIST field
		name CDATA #REQUIRED
		null (0|1) #IMPLIED>

<!-- Raw SQL -->
<!ELEMENT sql (query|drop|dropindex|rename)*>
<!ELEMENT query (#PCDATA)>
	<!-- The "driver" attribute can specify several drivers using comma separators. -->
	<!ATTLIST query
		driver CDATA #IMPLIED>

<!-- Schema operations -->
<!ELEMENT drop EMPTY>
	<!ATTLIST drop
		table CDATA #REQUIRED
		column CDATA #IMPLIED>
<!ELEMENT dropindex EMPTY>
	<!ATTLIST dropindex
		table CDATA #REQUIRED
		index CDATA #REQUIRED
		ifexists CDATA #IMPLIED>
<!ELEMENT rename EMPTY>
	<!ATTLIST rename
		table CDATA #REQUIRED
		column CDATA #IMPLIED
		to CDATA #REQUIRED>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.0.0_postupdate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * 3.0.0_postupdate.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * 3.0.0 post database updates XML file.
  -->
<data>
	<sql><!-- Issue #1208: Remove signoffs. -->
		<drop table="signoffs" />
		<query>DELETE FROM notifications WHERE assoc_type=1048582</query><!-- ASSOC_TYPE_SIGNOFF -->
		<query>DELETE FROM notifications WHERE type = 16777226</query><!-- NOTIFICATION_TYPE_SIGNOFF_COPYEDIT -->
		<query>DELETE FROM notifications WHERE type = 16777228</query><!-- NOTIFICATION_TYPE_SIGNOFF_PROOF -->
	</sql>
	<sql><!-- Drop migration tables -->
		<drop table="article_galleys_migration" />
		<drop table="article_files_migration" />
		<drop table="articles_migration" />
		<drop table="article_supplementary_files" />
		<drop table="article_supp_file_settings" />
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.0.0_postupgrade_metrics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * dbscripts/xml/upgrade/3.0.0_postupgrade_metrics.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  -->
<data>
	<!-- synchronize the ASSOC_TYPE_ARTICLE constant to ASSOC_TYPE_SUBMISSION defined in PKPApplication -->
	<sql>
		<query>UPDATE metrics SET assoc_type = 1048585 WHERE assoc_type = 257</query>
	</sql>
	<!-- update the ASSOC_TYPE_SUPP_FILE = 262 constant to ASSOC_TYPE_SUBMISSION_FILE_COUNTER_OTHER = 531 defined in PKPApplication -->
	<sql>
		<query>UPDATE metrics SET assoc_type = 531 WHERE assoc_type = 262</query>
	</sql>

	<!-- fill the new metrics columns (assoc_object_type, assoc_object_id, pkp_section_id and representation_id) appropriately: -->
	<!-- insert section id for articles, article galleys and files - they all have submission_id in the table -->
	<sql>
		<query driver="mysql,mysqli">UPDATE metrics m, submissions s SET m.pkp_section_id = s.section_id WHERE m.submission_id IS NOT NULL AND s.submission_id = m.submission_id</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE metrics SET pkp_section_id = s.section_id FROM submissions s WHERE metrics.submission_id IS NOT NULL AND s.submission_id = metrics.submission_id</query>
	</sql>
	<!-- insert issue id for articles, article galleys and files - they all have submission_id in the table, ASSOC_TYPE_ISSUE = 259 -->
	<sql>
		<query driver="mysql,mysqli">UPDATE metrics m, published_submissions p SET m.assoc_object_type = 259, m.assoc_object_id = p.issue_id WHERE m.submission_id IS NOT NULL AND p.submission_id = m.submission_id</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE metrics SET assoc_object_type = 259, assoc_object_id = p.issue_id FROM published_submissions p WHERE metrics.submission_id IS NOT NULL AND p.submission_id = metrics.submission_id</query>
	</sql>
	<!-- insert issue id for issue galleys, ASSOC_TYPE_ISSUE = 259, ASSOC_TYPE_ISSUE_GALLEY = 261 -->
	<sql>
		<query driver="mysql,mysqli">UPDATE metrics m, issue_galleys ig SET m.assoc_object_type = 259, m.assoc_object_id = ig.issue_id WHERE m.assoc_type = 261 AND ig.issue_id = m.assoc_id</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE metrics SET assoc_object_type = 259, assoc_object_id = ig.issue_id FROM issue_galleys ig WHERE metrics.assoc_type = 261 AND ig.issue_id = metrics.assoc_id</query>
	</sql>
	<!-- insert representation id for article galleys, ASSOC_TYPE_REPRESENTATION = 521 -->
	<sql>
		<query>UPDATE metrics SET representation_id = assoc_id WHERE assoc_type = 521</query>
	</sql>
	<!-- insert representation id for galley files, ASSOC_TYPE_SUBMISSION_FILE = 515, ASSOC_TYPE_REPRESENTATION = 521 -->
	<sql>
		<query driver="mysql,mysqli">UPDATE metrics m, submission_files sf SET m.representation_id = sf.assoc_id WHERE m.assoc_type = 515 AND sf.file_id = m.assoc_id AND sf.assoc_type = 521</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE metrics SET representation_id = sf.assoc_id FROM submission_files sf WHERE metrics.assoc_type = 515 AND sf.file_id = metrics.assoc_id AND sf.assoc_type = 521</query>
	</sql>

	<!-- issue #1933, ASSOC_TYPE_REPRESENTATION = 521 should be accordingly replaced by ASSOC_TYPE_SUBMISSION_FILE = 515 -->
	<sql>
		<query driver="mysql,mysqli">UPDATE metrics m, submission_galleys sg SET m.assoc_type = 515, m.assoc_id = sg.file_id WHERE m.assoc_type = 521 AND sg.galley_id = m.assoc_id AND ((sg.remote_url IS NULL) OR (sg.remote_url = ''))</query>
		<query driver="postgres,postgres64,postgres7,postgres8,postgres9">UPDATE metrics SET assoc_type = 515, assoc_id = sg.file_id FROM submission_galleys sg WHERE metrics.assoc_type = 521 AND sg.galley_id = metrics.assoc_id AND ((sg.remote_url IS NULL) OR (sg.remote_url = ''))</query>
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.1.2_update.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * 3.1.2_update.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * 3.1.2.0 general updates.
  -->
<data>
	<!-- pkp/pkp-lib#2894 pkp/pkp-lib#4036 Set 0 review ratings to NULL -->
	<sql>
		<query>UPDATE review_assignments SET quality = NULL WHERE quality = 0</query>
	</sql>
	<sql><!-- Move User from app-specific to shared lib -->
		<query>UPDATE filter_groups SET input_type='class::lib.pkp.classes.user.User[]' WHERE input_type='class::classes.user.User[]'</query>
		<query>UPDATE filter_groups SET output_type='class::lib.pkp.classes.user.User[]' WHERE output_type='class::classes.user.User[]'</query>
	</sql>
	<sql><!-- pkp/pkp-lib#4311 Change CC licenses to HTTPS URLs -->
		<query>UPDATE submission_settings SET setting_value='https://creativecommons.org/licenses/by-nc-nd/4.0' WHERE setting_value='http://creativecommons.org/licenses/by-nc-nd/4.0' AND setting_name='licenseUrl'</query>
		<query>UPDATE submission_settings SET setting_value='https://creativecommons.org/licenses/by-nc/4.0' WHERE setting_value='http://creativecommons.org/licenses/by-nc/4.0' AND setting_name='licenseUrl'</query>
		<query>UPDATE submission_settings SET setting_value='https://creativecommons.org/licenses/by-nc-sa/4.0' WHERE setting_value='http://creativecommons.org/licenses/by-nc-sa/4.0' AND setting_name='licenseUrl'</query>
		<query>UPDATE submission_settings SET setting_value='https://creativecommons.org/licenses/by-nd/4.0' WHERE setting_value='http://creativecommons.org/licenses/by-nd/4.0' AND setting_name='licenseUrl'</query>
		<query>UPDATE submission_settings SET setting_value='https://creativecommons.org/licenses/by/4.0' WHERE setting_value='http://creativecommons.org/licenses/by/4.0' AND setting_name='licenseUrl'</query>
		<query>UPDATE submission_settings SET setting_value='http://creativecommons.org/licenses/by-sa/4.0' WHERE setting_value='http://creativecommons.org/licenses/by-sa/4.0' AND setting_name='licenseUrl'</query>
	</sql>
	<!-- pkp/pkp-lib#4345 Ensure declined submissions are moved to archive -->
	<sql>
		<query>UPDATE submissions SET status=4 WHERE submission_id IN (SELECT e1.submission_id FROM edit_decisions e1 LEFT JOIN edit_decisions e2 ON (e2.submission_id = e1.submission_id AND e2.date_decided > e1.date_decided) WHERE e1.decision IN (4, 9) AND e2.edit_decision_id IS NULL) AND status=1</query><!-- STATUS_DECLINED; SUBMISSION_EDITOR_DECISION_DECLINE; SUBMISSION_EDITOR_DECISION_INITIAL_DECLINE; STATUS_QUEUED -->
	</sql>
	<!-- remove and rename old crossref status settings after the new deposit API integrat -->
	<sql>
		<query>DELETE FROM submission_settings WHERE setting_name = 'crossref::status' AND setting_value IN ('submitted', 'failed', 'completed')</query>
		<query>DELETE FROM submission_settings WHERE setting_name = 'crossref::statusUrl'</query>
		<query>UPDATE submission_settings SET setting_value = 'registered' WHERE setting_name = 'crossref::status' AND setting_name = 'found'</query>
	</sql>
	<sql><!-- pkp/pkp-lib#4561 Enable new metadata injection plugins -->
		<query>INSERT INTO plugin_settings (plugin_name, setting_name, setting_value, setting_type, context_id) SELECT 'googlescholarplugin', 'enabled', '1', 'bool', j.journal_id FROM journals j WHERE NOT EXISTS (SELECT ps.plugin_name FROM plugin_settings ps WHERE ps.plugin_name = 'googlescholarplugin' AND ps.context_id = j.journal_id)</query>
		<query>INSERT INTO plugin_settings (plugin_name, setting_name, setting_value, setting_type, context_id) SELECT 'dublincoremetaplugin', 'enabled', '1', 'bool', j.journal_id FROM journals j WHERE NOT EXISTS (SELECT ps.plugin_name FROM plugin_settings ps WHERE ps.plugin_name = 'dublincoremetaplugin' AND ps.context_id = j.journal_id)</query>
	</sql>
</data>

=== H-Alexa/IIT-Journal-project-using-OJS/dbscripts/xml/upgrade/3.0.0_pubId_settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data SYSTEM "../../../lib/pkp/dtd/xmlData.dtd">

<!--
  * 3.0.0_pubId_settings.xml
  *
  * Copyright (c) 2014-2021 Simon Fraser University
  * Copyright (c) 2003-2021 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * 3.0.0.0 updates for public identifiers plugins settings.
  -->
<data>
	<!-- Issue #1457: Public identifiers migration to OJS 3.0 -->
	<sql>
		<!--  DOI -->
		<query>UPDATE plugin_settings SET setting_name = 'doiRepresentationSuffixPattern' WHERE setting_name = 'doiGalleySuffixPattern'</query>
		<query>UPDATE plugin_settings SET setting_name = 'doiSubmissionSuffixPattern' WHERE setting_name = 'doiArticleSuffixPattern'</query>
		<query>UPDATE plugin_settings SET setting_name = 'enableRepresentationDoi' WHERE setting_name = 'enableGalleyDoi'</query>
		<query>UPDATE plugin_settings SET setting_name = 'enableSubmissionDoi' WHERE setting_name = 'enableArticleDoi'</query>
		<query>DELETE FROM plugin_settings WHERE setting_name = 'doiSuppFileSuffixPattern'</query>
		<query>DELETE FROM plugin_settings WHERE setting_name = 'enableSuppFileDoi'</query>
		<!--  URN -->
		<query>UPDATE plugin_settings SET setting_name = 'urnRepresentationSuffixPattern' WHERE setting_name = 'urnGalleySuffixPattern'</query>
		<query>UPDATE plugin_settings SET setting_name = 'urnSubmissionSuffixPattern' WHERE setting_name = 'urnArticleSuffixPattern'</query>
		<query>UPDATE plugin_settings SET setting_name = 'enableRepresentationURN' WHERE setting_name = 'enableGalleyURN'</query>
		<query>UPDATE plugin_settings SET setting_name = 'enableSubmissionURN' WHERE setting_name = 'enableArticleURN'</query>
		<query>UPDATE plugin_settings SET setting_name = 'urnNamespace' WHERE setting_name = 'namespace'</query>
		<query>UPDATE plugin_settings SET setting_name = 'urnCheckNo' WHERE setting_name = 'checkNo'</query>
		<query>UPDATE plugin_settings SET setting_name = 'urnCheckNo' WHERE setting_name = 'checkNo'</query>
		<query>DELETE FROM plugin_settings WHERE setting_name = 'urnSuppFileSuffixPattern'</query>
		<query>DELETE FROM plugin_settings WHERE setting_name = 'enableSuppFileURN'</query>
		<!--  Remove the journal setting -->
		<query>DELETE FROM journal_settings WHERE setting_name = 'enablePageNumber'</query>
		<query>DELETE FROM journal_settings WHERE setting_name = 'enablePublicArticleId'</query>
		<query>DELETE FROM journal_settings WHERE setting_name = 'enablePublicGalleyId'</query>
		<query>DELETE FROM journal_settings WHERE setting_name = 'enablePublicIssueId'</query>
		<query>DELETE FROM journal_settings WHERE setting_name = 'enablePublicSuppFileId'</query>
	</sql>
</data>
